package com.example.graduationproject.utils;


public class Constants {
    String reg= MAIN_URL + "ASSASD";
    public static String ip = "192.168.1.19";
    public static String MAIN_URL = "https://dbbe-188-0-103-57.ngrok-free.app/graduationProject";
    public static String registrationURL = "https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/registration.php";
    public static String loginURL = "https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/login.php";
    public static String checkAccountDoneURL = "https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/checkAccountDone.php";
    public static String updateTeacherInformation = "https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/updateTeacherInformation.php";
    public static String getNotificationsURL = "https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getNotifications.php";
    public static String URL = "https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/";
    public static String deleteConfirmedNotificationURL ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/deleteConfirmedAccountNotification.php";
    public static String updateParentInformation ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/updateParentInformation.php";
    public static String checkNotificationsChange ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/checkNotificationsChange.php";
    public static String getAllTeacherData ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getAllTeacherData.php";
    public static String getParentChildren ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getParentChildren.php";
    public static String addNewChild ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/addNewChild.php";
    public static String addNewTeacherMatching ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/addNewTeacherMatching.php";
    public static String getParentPostedTeacherMatchingData ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getTeacherMatchingData.php";
    public static String  getParentInformation ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getParentInformation.php";
    public static String  getParentPostedMatchingInformation ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getSpecificParentMatchingData.php";
    public static String updateParentPostedRequest ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/updateParentPostedRequest.php";
    public static String  getLastMatchingIdValue ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getLastTeacherMatchingId.php";
    public static String  insertTeacherPostRequest ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/insertTeacherPostRequest.php";
    public static String  getLastTeacherPostId ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getLastTeacherPostId.php";
    public static String  getTeacherPostedRequests ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getTeacherPostedRequests.php";
    public static String  getTeacherAvailability ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getTeacherAvailability.php";
    public static String  updateTeacherPostedRequest ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/updateTeacherPostedRequest.php";
    public static String  deleteTeacherPostedRequest ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/deleteTeacherPostedRequest.php";
    public static String  deleteParentPostedRequest ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/deleteParentPostedRequest.php";
    public static String  getAllTeacherPostedRequests ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getAllTeacherPostedRequestsForParent.php";
    public static String  getCurrentProfileData ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getCurrentProfileData.php";
    public static String  addParentSentRequestToTeacher ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/addParentSentRequestToTeacher.php";
    public static String  getTeacherReceivedRequests ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getTeacherReceivedRequests.php";
    public static String  setNotificationIsRead ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/setNotificationIsRead.php";
    public static String  getTeacherCoursesDates ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getTeacherCoursesDates.php";
    public static String  insertTeacherCourse ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/insertTeacherCourse.php";
    public static String  deleteRequestFromSent ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/deleteRequestFromSent.php";
    public static String  addTeacherSentRequestToParent ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/addTeacherSentRequestToParent.php";
    public static String  checkIfTeacherRequestSentBefore ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/checkIfTeacherRequestSentBefore.php";
    public static String  checkIfParentRequestSentBefore ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/checkIfParentRequestSentBefore.php";
    public static String  getParentReceivedRequest ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getParentReceivedRequest.php";
    public static String  getAllParentChildrenCoursesDates ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getAllParentChildrenCoursesDates.php";
    public static String  insertParentCourse ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/insertParentCourse.php";
    public static String  deleteParentRequestFromSent ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/deleteParentReceivedFromSent.php";
    public static String  deleteTeacherSentRequest ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/deleteTeacherSentRequest.php";
    public static String  deleteParentSentRequest ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/deleteParentSentRequest.php";
    public static String  getTeacherSpecificReceivedRequest ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getTeacherSpecificReceivedRequest.php";
    public static String  getAllTeacherCourses ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getAllTeacherCourses.php";
    public static String  getAllTeacherCoursesDatesAndTime ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getAllTeacherCoursesDatesAndTime.php";
    public static String  getAllParentCoursesDatesAndTime ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getAllParentCoursesDatesAndTime.php";
    public static String  removeNotification ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/removeNotification.php";
    public static String  getAllParentCourses ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getAllParentCourses.php";
    public static String  setCourseToDone ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/setCourseToDone.php";
    public static String  sendRemoveRequestToParent ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/sendRemoveRequestToParent.php";
    public static String  sendRemoveRequestToTeacher ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/sendRemoveRequestToTeacher.php";
    public static String  getSpecificTeacherCourse ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getSpecificTeacherCourse.php";
    public static String  getSpecificParentCourse ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getSpecificParentCourse.php";
    public static String  removeTeacherRequestCourseForParentAndTeacher  ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/removeTeacherRequestCourseForParentAndTeacher.php";
    public static String  sendDeclineRemovingRequestNotificationToTeacher  ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/sendDeclineRemovingRequestNotificationToTeacher.php";
    public static String  sendDeclineRemovingRequestNotificationToParent  ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/sendDeclineRemovingRequestNotificationToParent.php";
    public static String  removeTeacherRequestCourseForParentAndTeacher2  ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/removeTeacherRequestCourseForParentAndTeacher2.php";
    public static String  getSpecificDeclinedCourseForTeacher  ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getSpecificDeclinedCourseForTeacher.php";
    public static String  getSpecificDeclinedCourseForParent  ="https://dbbe-188-0-103-57.ngrok-free.app/graduationProject/getSpecificDeclinedCourseForParent.php";

    public static final String PREF_NAME = "GRADUATION_PROJECT_SHARED_PREFERENCE";

}
